//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheNight_JustBuy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComment
    {
        public int ProductCommentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Content { get; set; }
        public Nullable<int> VotedMark { get; set; }
        public Nullable<System.DateTime> CommentedDate { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
